#!/bin/sh
#
# Adapted by: Miguel Salcedo <imiguelsalcedo at hotmail dot com>
# To complement IcecastKH-autoinstaller.
# icecast This shell script takes care of starting and stopping
# the icecast multimedia streaming system.
#
# config: /usr/local/etc/icecast.xml

# Source function library.
. /etc/rc.d/init.d/functions

[ -x /usr/local/bin/icecast ] || exit 0

# See how we were called.
case "$1" in
start)
# Start daemon.
echo -n $"Starting icecast streaming daemon: "
daemon "/usr/local/bin/icecast -c /usr/local/etc/icecast.xml -b"
RETVAL=$?
echo
[ $RETVAL -eq 0 ] && touch /var/lock/subsys/icecast
#/etc/icecast/ices-start     (for ices)
;;
stop)
# Stop daemon.
echo -n $"Shutting down icecast streaming daemon: "
#/etc/icecast/ices-stop      (for ices)
killproc icecast
RETVAL=$?
echo
[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/icecast
;;
status)
status icecast
RETVAL=$?
;;
restart)
$0 stop
$0 start
;;
reload)
echo -n $"Reloading icecast: "
killproc icecast -HUP
RETVAL=$?
echo
;;
condrestart)
[ -f /var/lock/subsys/icecast ] && restart || :
;;
*)
echo $"Usage: $0 {start|stop|status|restart|reload}"
RETVAL=1
;;
esac

exit $RETVAL
